export const ActionsConstants ={
    'SET_EMPLOYEES':'SET_EMPLOYEES',
    'SET_EMPLOYEE':'SET_EMPLOYEE',
    'GET_ALL_EMPLOYEE':'GET_ALL_EMPLOYEE',
    'GET_INDIVIDUAL_EMPLOYEE':'GET_INDIVIDUAL_EMPLOYEE',
}
